---
abstract: 'Handle basic communication with Google services'
author:
  - 'Alan Young <harleypig@gmail.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Scalar::Util: 0
  Test::CheckDeps: 0.002
  Test::More: 0.94
  Test::Most: 0
  Test::NoWarnings: 0
  Test::UseAllModules: 0
  perl: 5.004
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Google-GData
no_index:
  directory:
    - t
    - xt
requires:
  Carp: 0
  Class::Accessor: 0
  Class::ErrorHandler: 0
  LWP::UserAgent: 0
  base: 0
  strict: 0
  warnings: 0
resources: {}
version: 0.03
